### PR TITLE
emmyLua autocomplete

### PR DESCRIPTION
**Pull request by d954mas**
Hi. I never use fmod before but i want to try it. Before start, I make a lua headers for emmyLua autocomplete. It worked. 
But i have some questions about binding (mark it TODO NEED HELP in fmod_headers.lua).

Thanks.

### CODE REVIEW

**Comment by dapetcu21** [comment]
Hi! It's cool that you made this, but keep in mind that this follows the 1.x FMOD API. Many of the TODOs in your file point to the 2.x FMOD documentation.

In other news, when I next have some time to maintain this, I'm thinking to write an automated parser and bindings generator for the FMOD headers, which could be leveraged for things like this as well.

**Comment by d954mas** [comment]
It makes sense. I will check 1.x Api. Why you use 1 instead of 2?

**Comment by dapetcu21** [comment]
Because 2 was released yesterday

**Comment by dapetcu21** [comment]
By the way. While I appreciate the work that you put in, It's very unlikely I will merge this PR. Merging this into the main project would mean having yet another thing to maintain and update when FMOD APIs change (like now). If something like this could be generated automatically, I would have no problem with it, but I won't merge something I know I won't have the time to maintain.

**Comment by d954mas** [comment]
It ok. I always can work on it in fork. If i have questions i will ask you)

**Pull request closed without merging**
